# Decap CMS configuration for WYWA FI-RE weekly updates
backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: updates/public/uploads
public_folder: /updates/uploads

collections:
  - name: updates
    label: Weekly Updates
    label_singular: Update
    folder: updates/src/content/updates
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "updates/{{slug}}/"
    editor:
      preview: true
    summary: "{{title}} — {{year}}-{{month}}-{{day}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Summary, widget: text, required: false, hint: "One sentence intro shown on the listing page (≤ 240 characters)." }
      - { name: date, label: Publish Date, widget: datetime, time_format: false }
      - { name: author, label: Author, widget: string, default: "WYWA FI-RE Team" }
      - { name: heroImage, label: Hero Image, widget: image, required: false, hint: "Shown at the top of the update. Optimise for 1600 × 900." }
      - { name: heroImageAlt, label: Hero Image Alt Text, widget: string, required: false }
      - { name: heroVideo, label: Hero Video (optional), widget: string, required: false, hint: "Provide a relative path (e.g. /updates/uploads/alert.mp4) or leave blank." }
      - { name: tags, label: Tags, widget: list, allow_add: true, required: false }
      - { name: featured, label: Featured, widget: boolean, default: false, required: false, hint: "Pin to the top of the updates overview." }
      - { name: draft, label: Draft, widget: boolean, default: false, required: false, hint: "Keep unchecked to publish the update." }
      - { name: body, label: Body, widget: markdown, hint: "Use Markdown for text, and insert videos or GIFs with the media library." }